### PR TITLE
Transfinite Recursion (part 2)

### PR DESCRIPTION
**Pull request by sankalpgambhir**
*This time, it's back for revenge.*

What we have:
:heavy_check_mark: Well Ordered Induction
:heavy_check_mark: Well Ordered Recursion
:heavy_check_mark: Transfinite Induction
:gear: Transfinite Recursion

Some lemmas about orderings using `Sorry` will be filled in later :eyes: . 

Any fixes or changes:
:+1: Relies on #159 and #160 locally, please don't merge yet <- these were merged :)
:gear: Fix `UniqueComprehension` breaking due to assumptions after #160 .

### CODE REVIEW

**Comment by SimonGuilloud** [comment]
neat

**Comment by sankalpgambhir** [comment]
pls merge we give up

more lemmas will come later

**Comment by sankalpgambhir** [comment]
(It is more important to have the theory and proof refactorings in main soon)

**Review by SimonGuilloud — APPROVED** [review]
LGTM!

**Pull request merged**
