### PR TITLE
Various improvements  and refactoring

### PR DESCRIPTION
**Pull request by SimonGuilloud**
-New package utilities containing the KernelHelper and tptp, and suitable for ace.
-Theorems now require the target statement (related to https://github.com/epfl-lara/lisa/issues/9)
    This is still a bit cheaty or cumbersome without a full parser for the kernel.
-Various other corrections, merge conflicts resolved...
-Keep function and predicate label definitions distinct in the running theory for now, to keep knowledge as much as possible.

### CODE REVIEW

**Comment by FlorianCassayre** [comment]
Beware, this PR contains commits that were already merged (but have different hashes). It seems [827f7b2](https://github.com/epfl-lara/lisa/pull/19/commits/827f7b20f5a43b0dbadc43411b2169d1706c0dfb) and later are the commits to keep, the rest can be discarded (using e.g. _interactive rebase_).

**Comment by SimonGuilloud** [comment]
> Beware, this PR contains commits that were already merged (but have different hashes). It seems [827f7b2](https://github.com/epfl-lara/lisa/pull/19/commits/827f7b20f5a43b0dbadc43411b2169d1706c0dfb) and later are the commits to keep, the rest can be discarded (using e.g. _interactive rebase_).
Honestly I don't understand what you're refering to and how it would work, except that I had indeed a lot of weird issues while merging, yes. ^^'

**Comment by FlorianCassayre** [comment]
So, usually you should try to keep your local branch up to date with `origin/main`. To do so you should rebase your local branch onto the remote one whenever there are new commits available on the origin. The reason behind doing a _rebase_ rather than a _merge_ is to keep the history clean: a merge will create a merge commit, while a rebase will re-attach your local commits to the newer remote ones. A clean history makes it much easier to review the changes (and PRs are guaranteed to be conflict-less).

I looked at your branch, I think it can be fixed using _cherry picking_. I can try to author it for you this afternoon.

**Comment by SimonGuilloud** [comment]
I see what a rebase does, but I fail to see what led to duplicates of commits, or how to solve it, or why it is even a thing... The instructions github is giving are the exact same as the one I did on my fork yesterday and it should be sitrictly ahead.

**Comment by FlorianCassayre** [comment]
Check out the branch [`pr-19`](https://github.com/FlorianCassayre/lisa/tree/pr-19) in my repository: I rewrote the history such that it contains your five commits and it is up-to-date with `main` (if you decide to use it **do not** merge it with your branch; instead replace it altogether and force-push).

I believe the main issue is that you are working within your `main` branch for these PRs. Instead, you should always start on a new branch, ideally from the latest commit on `origin/main`.

**Comment by SimonGuilloud** [comment]
Ok. But that's still very obscure. Commits such as https://github.com/epfl-lara/lisa/pull/19/commits/1239fb32ae902ffb35b8547f5ba735582340b80f were push on my main branch, and from there on the origin so why is github trying to repush them a second time?

I should have simply taken the changes regarding ConstantLabel and reimplement it on my branch, rather than spending two hours fixing every single file for actually non-existing conflicts ^^'

**Comment by SimonGuilloud** [comment]
> I believe the main issue is that you are working within your `main` branch for these PRs. Instead, you should always start on a new branch, ideally from the latest commit on `origin/main`.

Is that essentially equivalent to merging without rebasing? If so that looks significantly simpler.

**Comment by FlorianCassayre** [comment]
> > Check out the branch [`pr-19`](https://github.com/FlorianCassayre/lisa/tree/pr-19) in my repository: I rewrote the history such that it contains your five commits and it is up-to-date with `main` (if you decide to use it **do not** merge it with your branch; instead replace it altogether and force-push).
> 
> Thanks! I suppose it is essentially equivalent to merging without rebasing? If so that looks significantly simpler.

What you should do is store your current changes in a new branch (just in case), then delete your `main` and checkout `pr-19` as your new `main`.
In the future you would want to avoid pushing directly to your `main`: this branch should always be behind or at the same level as `origin/main`, never forward.

Below in an illustration of what happened:

image

Now if you try to merge PR2 the blue commit will be included, even though it already exists under a different hash (orange) on `origin/main`. The solution would have been to reset your personal `main` branch before doing more work but that would prevent you from working on several PRs at a time, which is why it is preferable to have one branch per PR.

**Comment by SimonGuilloud** [comment]
I mostly see, thanks. Though this picture looks self consistent to me, changes are integrated to the origine sequentially in a consistent way...

**Comment by FlorianCassayre** [comment]
If you look at the history, you'll see that the latest commits have the form
> _XXX_ authored and _SimonGuilloud_ committed

which indicates that you were using rebase-merge when merging PRs.

**Comment by SimonGuilloud** [comment]
> If you look at the history, you'll see that the latest commits have the form
> 
> > _XXX_ authored and _SimonGuilloud_ committed
> 
> which indicates that you were using rebase-merge when merging PRs.


Indeed, I was advised to do so.

**Pull request merged**
