### PR TITLE
Added tests to Substitution functions

### PR DESCRIPTION
**Pull request by lighthea**
Added tests to test both functionalities of simple formulas/terms of each type and corner cases for every substitution functions.
Until issues #74, #80, and #81 are closed 4 tests are commented out

### CODE REVIEW

**Comment by SimonGuilloud** [comment]
you could retry the tests which are not passing now :)

**Comment by cache-nez** [comment]
> Until issues 74, 80, and 81 are closed 4 tests are commented out

You can refer to issues like that: #81, then this reference appears on the issue page (in this case, I'll know I'm blocking your PR!). There is also an alternative to commenting tests: one can write `ignore(name) { body }` instead of `test(name) { body }`, which will produce an output (making it easier to remember about and investigate the disabled test) without failing the CI.

**Comment by lighthea** [comment]
Thank you for the formatting tips, the tests depending on the isSame problem are running correctly now

**Comment by SimonGuilloud** [comment]
Hmmm why are some cases removed from UNconditionalizeProof?

**Comment by sankalpgambhir** [comment]
Substitution tests were written in #106.

**Pull request closed without merging**
